# -*- coding: utf-8 -*-
"""Represetasi_Pengetahuan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18H4HVlMiX8xtYJb0yNVn0XVhKtzvAiTK
"""

pip install pytholog

import pytholog as pl

"""# ![image.png](attachment:image.png)"""

new_kb = pl.KnowledgeBase("silsilah_keluarga")
new_kb(["female(pam)",
        "female(liz)",
        "female(pat)",
        "female(ann)",
        "male(tom)",
        "male(bob)",
        "male(jim)",
        
        "parent(pam, bob)",
        "parent(tom, bob)",
        "parent(tom,liz)",
        "parent(bob, ann)",
        "parent(bob, pat)",
        "parent(pat, jim)",
        
        "mother(X,Y):-parent(X,Y),female(X)",
        "kakek(X,Z):-parent(X,Y),parent(Y,Z),male(X)"])

new_kb.query(pl.Expr("mother(X, bob)"))

new_kb.query(pl.Expr("kakek(X, ann)"))

from time import time
print(new_kb.query(pl.Expr("kakek(X, ann)")))

"""# ![image.png](attachment:image.png)"""

new_kb = pl.KnowledgeBase("flavor")
new_kb(["laki(alan)",
        "laki(jhon)",
        "laki(mike)",
        "laki(doni)",
        "laki(anton)",
        "laki(andre)",
        "perempuan(diana)",
        "perempuan(dara)",
        "perempuan(silvi)",
        "perempuan(melly)",
        "perempuan(rossa)",
        
        "orangtua(alan,dara)",
        "orangtua(alan,jhon)",
        "orangtua(diana,dara)",
        "orangtua(diana,jhon)",
        "orangtua(mike,melly)",
        "orangtua(mike,doni)",
        "orangtua(mike,anton)",
        "orangtua(dara,melly)",
        "orangtua(dara,doni)",
        "orangtua(dara,anton)",
        "orangtua(jhon,rossa)",
        "orangtua(jhon,andre)",
        "orangtua(silvi,rossa)",
        "orangtua(silvi,andre)",
        
        "ibu(X,Y):-orangtua(X,Y),perempuan(X)",
        "ayah(X,Y):-orangtua(X,Y),laki(X)",
        
        "kakek(X,Z):-orangtua(X,Y), orangtua(Y,Z), laki(X)",
        "nenek(X,Z):-orangtua(X,Y),orangtua(Y,Z),perempuan(X)",
        
        "cucuperempuan(X,Z):-orangtua(Z,Y),laki(Y),orangtua(Y,X),perempuan(X)",
        "cuculakilaki(X,Z):-orangtua(Z,Y),orangtua(Y,X),laki(Y),laki(X)",
        
        "saudaraperempuan(X,Y):-orangtua(Z,Y),orangtua(Z,X), perempuan(X)",
        "saudaralaki(X,Y):-orangtua(Z,Y),orangtua(Z,X), laki(X)",
        
        "paman(X,Y):-orangtua(Y,Z),saudaralaki(Y,X), laki(X)"])

new_kb.query(pl.Expr("laki(andre)"))

new_kb.query(pl.Expr("kakek(X,doni)"))

new_kb.query(pl.Expr("saudaralaki(X,dara)"))

new_kb.query(pl.Expr("paman(X,rossa)"))